config/routes.rb
Rails.application.routes.draw do

  get 'animals/show'

  resources :classifications do
    resources :animals
  end

   root "classifications#index"

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :classification
  has_many :common_names
  #validates_format_of :name, :without => /\A^d\z/

  def recent?
    extinction_date > 1900
  end

  def to_param
    name
  end

  def has_image
    image_url.present?    
  end 

  def self.find(input)
    input.to_i == 0 ? find_by_name(input) : super
  end
  
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :animals
  #validates_format_of :name, :without => /\A^d\z/

  def to_param
    name
  end

  def self.find(input)
    input.to_i == 0 ? find_by_name(input) : super
  end
  
end

app/models/common_name.rb
class CommonName < ActiveRecord::Base
  belongs_to :animal

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  def show
    @animal = Animal.find(params[:id])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  def index
    @classifications = Classification.all
  end

  def show
    @classification = Classification.find(params[:id])
  end
  
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>

  <ul>
    <li> Scientific Name: <%= @animal.name %></li>
      <% @animal.common_names.each do |a|%>

        <li> CommonName: <%= a.name %> </li>
      <% end %>
    <li><%= @animal.recent?? h("Recent") : h("Not Recent") %></li>
    <li><%= link_to("URL",@animal.url)%></li>
     
    <% if @animal.has_image %>
      <%= image_tag(@animal.image_url) %>
    <% end %>

  </ul>

<p><%= link_to("Back to the list of Classifications", classifications_path)%></p>

app/views/classifications/index.html.erb
<h1>Classifications</h1>

<ul>
  <% @classifications.each do |c| %>
    <li><h2><%= link_to(c.name , classification_path(c)) %></h2></li>
    <p><%="Quantity: "+c.animals.count.to_s%></p>
  <% end %>

</ul>

app/views/classifications/show.html.erb
<h1><%= @classification.name %></h1>

<ul>
  <% @classification.animals.each do |a| %>
    <li><h2><%= link_to(a.name , classification_animal_path(@classification,a)) %></h2></li>
    <hr>
     

   
  <% end %>
</ul>

<p><%= link_to("Back to the list of Classifications", classifications_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Extinctions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>